### PR TITLE
Issue #2 Added Mewtwo

### PR DESCRIPTION
**Pull request by RohanHBTU**
issue #2

### CODE REVIEW

**Comment by dsasaank-369** [comment]
Add the code inside the pokemon-cards section

**Comment by RohanHBTU** [comment]
I have included mewtwo inside pokemon cards

**Comment by RohanHBTU** [comment]
Please merge this PR as soon as possible.

**Comment by dsasaank-369** [comment]
There is no class name called "electric" in CSS. Please resolve that issue

**Comment by RohanHBTU** [comment]
Now, I have added purple class and the required.

**Comment by RohanHBTU** [comment]
If there is any issue still left with this PR, please report otherwise merge this PR.

**Comment by dsasaank-369** [comment]
Add the card inside existing pokemon cards class and do not add seperately

**Pull request closed without merging**
