### PR TITLE
Squirtle Card added

### PR DESCRIPTION
**Pull request by AditiBendre**
Made changes to index.html and styles.css.

### CODE REVIEW

**Comment by dsasaank-369** [comment]
Please change the name of the color class to any other name as blue is already existing.

**Comment by AditiBendre** [comment]
Changed the name from blue to water. Do i have to change it in the html file also?

**Comment by AditiBendre** [comment]
Changed the name from blue to water in html.index also so that the color applies.

**Comment by dsasaank-369** [comment]
Thank you for showing interest in contributing to this repository. If you liked it, please star the repository.

**Comment by AditiBendre** [comment]
Hii
Could you please tell me why is this issue excluded from hacktoberfest 2022?

**Pull request merged**
