### PR TITLE
Added Alolan Marowak

### PR DESCRIPTION
**Pull request by AnshSinghSonkhia**
Merge this ASAP!

### CODE REVIEW

**Comment by AnshSinghSonkhia** [comment]
Hey @dsasaank-369,
Could you please merge this PR to add Alolan Marowak? 
**This is RARE.**

THANKS

**Comment by AnshSinghSonkhia** [comment]
Hey @dsasaank-369,
## Please **Add `hacktoberfest-accepted`** label.
Thanks for your precious time!

**Comment by AnshSinghSonkhia** [comment]
Hey @dsasaank-369, kindly add `hacktoberfest-accepted` Label!!

**Comment by dsasaank-369** [comment]
Thank you for showing interest in contributing to this repository. If you liked it, please star the repository.

**Pull request merged**
